### ISSUE TITLE
add_case and add_ground missing

### ISSUE THREAD

**Issue by mzillich** [squirrel-project/squirrel_manipulation#112]
`CMakeLists.txt` refers to `src/add_case.cpp` and `src/add_ground.cpp`, but these are missing.

**Comment by ipa-nhg** [comment]
This was added in the PR : https://github.com/squirrel-project/squirrel_manipulation/commit/1f701f43c372387a0fa8163d38fce35d1a4bbbee , the files should be on the robot  @edith-langer could you please add and push the missed files?

**Comment by ipa-nhg** [comment]
@edith-langer @mzillich could you please add and commit the missed files?
HotFix https://github.com/squirrel-project/squirrel_manipulation/pull/117

**Comment by edith-langer** [comment]
Didn't see your comment in June, sorry. Unfortunately, we can't push the files. As you know the robot is in Lisbon and we have just an older backup which does not include those files. Who wrote the files? Were they just on our robot?
