### ISSUE TITLE
Deps on uibk_robot_driver

### ISSUE THREAD

**Issue by ghost** [squirrel-project/squirrel_manipulation#114]
@ipa-nhg uibk_robot_driver is gone, right? Does squirrel_manipulation now compile? I guess it shouldn't, right, as there are still some packages with deps on the old driver (at least kinesthetic_teaching). Or are there still pending pull requests? @smhaller @mzillich

**Comment by ipa-nhg** [comment]
Well this has never compile, at least for me. But if we switch to the new driver and use squirrel_motion_planning this repository has to be cleaned... who can do that?

**Comment by ghost** [comment]
I suggest at the next integration meeting. Is there some way to create a dependency graph of the packages? That would easy things horribly. And then the package developer will have to take care of that.But again - I suggest a slot at the integration meeting with everyone there.

**Comment by ipa-nhg** [comment]
I think the maintainer of each package should check the software and , if it is possible, clean it. I can try to generate a graph and send to you, but until the dependencies to kukadu are not removed I can not check with my systems the software and the consistency of the dependencies.
Anyway the dependency to uibk_robot_driver can be already removed, I checked it and only kinestatic_teaching and uibk_planning_test depend on uibk_robot_driver. uibk_planning_test doesn't need it at all and kinestatic_teaching include the package to launch  a controller.launch file that didn't exists on uibk_robot_driver, I believe no one is using the file... https://github.com/squirrel-project/squirrel_manipulation/pull/115

**Comment by ghost** [comment]
That's why the next integration meeting would be ideal for that. I apparently do not seem to be the maintainer of squirrel_manipulation, as I mostly get no updates (except for issues I get assigned to). The problem is that removing uibk_robot_driver and kukadu makes squirrel_manipulation useless as it won't compile anymore at all. So please let's do that during a meeting and not now. I planning to write an ICRA paper and am going horribly crazy about that small piece of shitty scrap metal by trying to use the arm and some other components. Just does not work most of the time if not only isolated parts of the system are necessary. Also, we have a meeting today to bring that up.
