### ISSUE TITLE
Clean squirrel_manipulation packages

### ISSUE THREAD

**Issue by ipa-nhg** [squirrel-project/squirrel_manipulation#116]
Some of the software is obsolete and the dependency to kukadu should be removed. I generated the dependencies graphs for all the packages, may this can help:

![kinesthetic_teaching](https://user-images.githubusercontent.com/650568/29860825-9c0d003c-8d67-11e7-9448-b097cc1c2551.png)
![squirrel_grasping](https://user-images.githubusercontent.com/650568/29860829-a162e538-8d67-11e7-8e50-2ee7abf439e9.png)
![squirrel_handovers](https://user-images.githubusercontent.com/650568/29860833-a424c7d2-8d67-11e7-979e-943a8a6fa649.png)
![squirrel_manipulation_waypoint](https://user-images.githubusercontent.com/650568/29860838-a860e222-8d67-11e7-9f22-3220b3454c25.png)
![squirrel_moveit_utils](https://user-images.githubusercontent.com/650568/29860852-b1e2808a-8d67-11e7-88ff-bd2c830b53ba.png)
![squirrel_object_manipulation](https://user-images.githubusercontent.com/650568/29860855-b3913c50-8d67-11e7-9700-73a56c32ab17.png)
![squirrel_placement](https://user-images.githubusercontent.com/650568/29860858-b6e792b4-8d67-11e7-854c-e8027e8f52e8.png)
![squirrel_ptp_server](https://user-images.githubusercontent.com/650568/29860862-b8840ac6-8d67-11e7-8c09-9b0f0ff072cc.png)
![tuw_moveit_config](https://user-images.githubusercontent.com/650568/29860867-bb152a04-8d67-11e7-95bf-da9b6644a75c.png)
![uibk_moveit_config](https://user-images.githubusercontent.com/650568/29860870-bd674fb2-8d67-11e7-9f00-c32deb89db12.png)
![uibk_moveit_config_sh](https://user-images.githubusercontent.com/650568/29860873-bf2e80a4-8d67-11e7-8131-dc155b007db0.png)
![uibk_planning_test](https://user-images.githubusercontent.com/650568/29860875-c156558c-8d67-11e7-8b5a-ab0fd97c1e07.png)

**Comment by ghost** [comment]
Thx! Will study it in detail these days.

**Comment by ipa-nhg** [comment]
Updates here?

**Comment by ghost** [comment]
Not yet. Still waiting for the planner to be integrated. If this is done, the manipulation stack will be cleaned. Hopefully by the end of this year (but most likely earlier).

**Comment by tpatten** [comment]
We will need this to be done by mid next week because we plan to do grasping in the next episode with the children in the following week. @lokalmatador once the motion planner is integrated how long do you think it will take to clean the repository and for it to be compiled without kukadu? @philkark what is the status with the motion planner?

**Comment by ghost** [comment]
Well that probably won't work out. Estimated delivery date of the robot is Thursday. then I guess it'll take us 1-2 days to fix everything. Which makes next Tuesday. with the planner integrated, I guess it takes me 2-3 days to make everything running again. BUT, we have an event next Thursday  for which we have to prepare a few things. So maybe expect the week after next week. I'll see what I can do. It all depends on when we receive the robot, the final integration of the planner, and last but not least, if all the hardware works. Also, be aware that we probably won't test with the KCL hand as for now it's not planned to mount that on our robot.

**Comment by tpatten** [comment]
Hmm ok. Also, it may take even longer that 1-2 days to fix everything...
I will discuss with @mzillich about how we go ahead with grasping without the manipulation package. For our purposes we can probably get something together but we would like to avoid this hack-situation as much as possible while doing the episodes.

**Comment by mzillich** [comment]
TUW, UIBK and ALUFR should have a small integration meeting for that I think, mid November or so.
So that we can properly test all grasping, KCL and Softhand.

**Comment by ghost** [comment]
For UIBK, I guess late November is better, as we have two upcoming events to plan for and one needs the robot - one of those is participate in the European Robotics Week which for us is the 23 of November. After that, things should be fine and a meeting should be easy and straight forward to schedule.

**Comment by ghost** [comment]
shit, didn't want to close! Sorry, pressed the wrong button!

**Comment by mzillich** [comment]
ok, makes sense.

**Comment by tpatten** [comment]
Can we close this now?

**Comment by ghost** [comment]
Just doing a test with the update server, if that works, I guess we can close it.

**Comment by ipa-nhg** [comment]
done by https://github.com/squirrel-project/squirrel_manipulation/pull/119 

Thanks!!!!! :smile:
