### ISSUE TITLE
Cleanup Repository

### ISSUE THREAD

**Issue by ipa-rmb** [squirrel-project/squirrel_manipulation#77]
I had a phone call with Simon and we agreed on having a meeting for introducing the new controller (packages: uibk_arm_controller, uibk_arm_model) to the team and cleaning up this package from outdated packages. Furthermore, simulation has to be adapted for the new controller and the new arm model needs to be tested in simulation. The meeting date will be set at the GA end of June.

**Comment by ghost** [comment]
I think this can be closed.
